"""Display remains readable in an actual unactivated Release; operations still deny.

Uses the real DLL SDO registrations via LicensingIntegrationBridge. No activation,
issuer enrollment, certificate installation, or TPM writes are invoked.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def license_snapshot() -> dict:
    directory = Path(os.environ.get("ProgramData", r"C:\ProgramData")) / "TubeDesigner/Licensing"
    return {str(item.relative_to(directory)): digest(item) for item in directory.rglob("*") if item.is_file()} if directory.exists() else {}


def main() -> None:
    repo = Path(__file__).resolve().parents[6]
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime-root", type=Path, default=repo / "src/x64/Release")
    parser.add_argument("--report-dir", type=Path, default=repo / "output/tests/tube-designer-license-readonly")
    parser.add_argument("--host", type=Path)
    args = parser.parse_args()
    runtime, report_dir = args.runtime_root.resolve(), args.report_dir.resolve()
    host = args.host.resolve() if args.host else report_dir / "native-host/LicensingIntegrationBridge.exe"
    assert host.is_file(), f"Missing native host: {host}; build LicensingIntegrationBridge or pass --host."
    before_license = license_snapshot()
    assert "license.tdlic" not in before_license, "This regression requires an unactivated machine; existing certificates are never changed."
    report_dir.mkdir(parents=True, exist_ok=True)
    report = {"status": "RUNNING", "runtimeRoot": str(runtime), "scope": "actual enforced Release DLL SDOs with isolated in-memory scene and user data", "readCalls": [], "expectedDenials": [], "handlerValidations": [], "limitations": ["No desktop/CEF activation or TPM enrollment is performed.", "Read catalogs and empty scene are tested; saved display recipes are not newly generated by this fixture."]}
    environment = dict(os.environ)
    environment["PATH"] = str(runtime) + os.pathsep + environment.get("PATH", "")
    with (report_dir / "readonly-host-stderr.log").open("w", encoding="utf-8") as stderr, (report_dir / "readonly-invocations.jsonl").open("w", encoding="utf-8") as transcript:
        process = subprocess.Popen([str(host), "--configured-unactivated"], cwd=runtime, env=environment,
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=stderr, text=True, encoding="utf-8", creationflags=subprocess.CREATE_NO_WINDOW)
        call_id = 0

        def invoke(method: str, payload: dict | None = None, expected: str = "success") -> dict:
            nonlocal call_id
            call_id += 1
            request = {"id": call_id, "method": method, "payload": payload or {}}
            process.stdin.write(json.dumps(request, ensure_ascii=False) + "\n")
            process.stdin.flush()
            line = process.stdout.readline()
            assert line, f"Host stopped on {method}; inspect readonly-host-stderr.log"
            response = json.loads(line)
            transcript.write(json.dumps({"request": request, "response": response}, ensure_ascii=False) + "\n")
            transcript.flush()
            assert response["id"] == call_id
            if expected == "denial":
                assert not response["ok"] and "Cannot access license file" in response.get("error", ""), response
                report["expectedDenials"].append({"method": method, "payload": payload or {}})
                return response
            if expected == "validation":
                assert not response["ok"] and "Cannot access license file" not in response.get("error", "") and "未授权" not in response.get("error", ""), response
                report["handlerValidations"].append({"method": method, "error": response["error"]})
                return response
            assert response["ok"], response
            return response["result"]

        try:
            policy = invoke("Inspect.Policy")
            assert policy["authorizationEnforced"] and policy["configured"] and not policy["developmentBypass"], policy
            report["policy"] = policy
            status = invoke("TubeDesignerLicensing.Status")
            assert not status["activated"] and not any(status["capabilities"].values()), status
            report["capabilities"] = status["capabilities"]
            modules = invoke("Inspect.Modules")
            report["modules"] = {}
            for name, path in modules.items():
                assert os.path.normcase(str(Path(path).resolve())) == os.path.normcase(str(runtime / name))
                report["modules"][name] = {"path": path, "sha256": digest(Path(path))}
            before = invoke("Inspect.Scene")
            snapshot = invoke("TubeDesigner.List")
            assert snapshot["tubeDesigner"]["templates"], snapshot
            assert not snapshot["tubeDesigner"]["instances"], snapshot
            report["readCalls"].append("TubeDesigner.List")
            first_template = snapshot["tubeDesigner"]["templates"][0]["id"]
            descriptor = invoke("TubeDesigner.GetTemplateDescriptor", {"templateId": first_template})
            assert descriptor["template"]["id"] == first_template
            report["readCalls"].append("TubeDesigner.GetTemplateDescriptor")
            for method in ["ListUserData", "ListSystemProfiles", "ListComponentModels", "GetPunchTools", "GetAssemblyTemplates", "GetAssemblyProcessPlans", "GetPartDrawingTools", "ListNestingPartFiles"]:
                invoke("TubeDesigner." + method)
                report["readCalls"].append("TubeDesigner." + method)
            invoke("TubeDesigner.List", {"nestingOnly": True})
            invoke("TubeDesigner.List", {"includeManufacturingGeometry": False})
            assert invoke("Inspect.Scene") == before, "Read-only browsing mutated the empty scene or resource set"
            for method in ["GetProductAssemblyConnections", "GetProductAssemblyBindings", "ReadNestingResult", "GetPartDrawing"]:
                invoke("TubeDesigner." + method, expected="validation")
            for payload in [{"includeManufacturingGeometry": True}, {"includeManufacturingGeometry": True, "nestingOnly": True}]:
                invoke("TubeDesigner.List", payload, "denial")
            for method, payload in [
                ("GeneratePreview", {"templateId": first_template, "parameters": {}}),
                ("Disassemble", {}), ("GetBatchExcelAutomationSettings", {}), ("AddNestingStandardPart", {}), ("AddNestingPunchPart", {}),
                ("PreviewPunchWizard", {}), ("ApplyPunchWizard", {}), ("Nest", {}),
                ("ExportBatchExcelTemplate", {"targetPath": str(report_dir / "forbidden.xlsx")}),
                ("ExportComponentModel", {}), ("ExportProductTemplatePackage", {}), ("ExportProfile", {}),
                ("ExportNesting", {}), ("MachiningData", {"action": "preview"}), ("MachiningData", {"action": "create"}),
            ]:
                invoke("TubeDesigner." + method, payload, "denial")
            assert invoke("Inspect.Scene") == before
            assert license_snapshot() == before_license
            assert not (report_dir / "forbidden.xlsx").exists()
            invoke("Inspect.SeedLinkedProduct", {"templateId": first_template,
                "templateVersion": descriptor["template"]["version"],
                "parameters": {field["key"]: field["defaultValue"] for field in descriptor["template"]["parameters"]}})
            linked_before = invoke("Inspect.Scene")
            linked = invoke("TubeDesigner.List")
            assert linked["tubeDesigner"]["instances"][0]["name"] == "Saved product browse fixture"
            invoke("TubeDesigner.List", {"nestingOnly": True})
            assert invoke("Inspect.Scene") == linked_before
            report["linkedMissingManufacturingCacheDoesNotRebuild"] = True
            report["sceneUnchanged"] = True
            report["licenseStoreUnchanged"] = True
            report["status"] = "PASS"
        except Exception as error:
            report["status"] = "FAIL"
            report["error"] = str(error)
            raise
        finally:
            process.stdin.close()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()  # Only this runner's owned isolated test process.
                process.wait(timeout=10)
            report["hostExitCode"] = process.returncode
            report["invocationCount"] = call_id
            (report_dir / "readonly-report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Release unactivated read-only browsing regression passed: {len(report['readCalls'])} reads and {len(report['expectedDenials'])} protected denials.")


if __name__ == "__main__":
    main()
