<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'TubeDesignerTest'">
    <TargetName>SecurityWindowFramesBridge</TargetName>
    <OutDir>$(SolutionDir)..\tmp\security-window-frames-native\</OutDir>
    <IntDir>$(SolutionDir)..\tmp\security-window-frames-native\obj\</IntDir>
    <OutDir Condition="'$(ICAXInspectionBridgeOutputRoot)' != ''">$(ICAXInspectionBridgeOutputRoot)\</OutDir>
    <IntDir Condition="'$(ICAXInspectionBridgeOutputRoot)' != ''">$(ICAXInspectionBridgeOutputRoot)\obj\</IntDir>
    <ICAXInspectionBridgeSource Condition="'$(ICAXInspectionBridgeSource)' == ''">$(MSBuildProjectDirectory)\SecurityWindowFramesBridge.cpp</ICAXInspectionBridgeSource>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'TubeDesignerTest'">
    <ClCompile Remove="@(ClCompile)" />
    <ClCompile Include="$(MSBuildProjectDirectory)\..\..\..\..\pch.cpp"><PrecompiledHeader>Create</PrecompiledHeader></ClCompile>
    <ClCompile Include="$(ICAXInspectionBridgeSource)">
      <AdditionalIncludeDirectories>$(MSBuildProjectDirectory)\..\..\..\..\..\iCAX-Plugins\render;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemGroup>
</Project>
