import assert from "node:assert/strict";
import {moldApplicability,previewSectionAnalysis} from "../../apps/tube-designer/webpage/moldApplicability.mjs";
const descriptor={sectionAnalysis:{schemaVersion:1}};
assert.deepEqual(moldApplicability({},{}),[]);
assert.equal(moldApplicability(descriptor,{},undefined)[0].status,"unknown");
assert.deepEqual(moldApplicability(descriptor,{}, {applicable:true}),[]);
assert.equal(moldApplicability(descriptor,{}, {applicable:false,reason:"unsupported"})[0].message,"unsupported");
const item={};
const result={index:0,applicable:true,parameters:{wallThickness:2}};
const state={revision:2,features:[item],preview:{revision:2,sectionAnalyses:[result]}};
assert.equal(previewSectionAnalysis(state,item),result);
state.revision=3;
assert.equal(previewSectionAnalysis(state,item),undefined);
assert.equal(previewSectionAnalysis(state,{}),undefined);
state.revision=2;
state.draft={id:"draft"};
state.preview.includesDraft=true;
state.preview.sectionAnalyses.push({index:1,applicable:true});
assert.equal(previewSectionAnalysis(state,state.draft).index,1);
state.preview.includesDraft=false;
assert.equal(previewSectionAnalysis(state,state.draft),undefined);
console.log("Mould analysis display: success, rejection, pending and stale results passed.");
