import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {browserReportDirectory,importBrowserAsset,serveBrowserAsset} from './browserPackageRuntime.mjs';
const catalogue=JSON.parse(readFileSync(resolve(process.env.ICAX_NATIVE_SCENE_EVIDENCE||'output/tests/product-profile-labels-20261006','system-profiles.json')));
const {tubeDesignerCss}=await importBrowserAsset('apps/tube-designer/webpage/styles/tubeDesigner.css.mjs');
const {chromium}=await import('playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const output=browserReportDirectory('product-profile-labels-20261006/library-browser');
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.route('http://profile-library-retention.test/**',serveBrowserAsset);
 await page.goto('http://profile-library-retention.test/');
 await page.addStyleTag({content:tubeDesignerCss});
 await page.addStyleTag({content:'.cam-workbench{position:relative;display:grid;grid-template-columns:260px 1fr 430px;height:900px}.cam-viewport{position:relative;background:#152b33}.cam-info-pane{height:800px;overflow:auto}'});
 await page.evaluate(async catalogue=>{
  const library=await import('/src/apps/tube-designer/webpage/profileLibrary.mjs');
  const {bindProfileParameterDiagrams}=await import('/src/apps/tube-designer/webpage/profileParameterDiagram.mjs');
  const {bindDiagramDragging}=await import('/src/apps/tube-designer/webpage/floatingParameterDiagram.mjs');
  const view={activeAreaId:'profiles',tubeDesignerSystemProfiles:catalogue,tubeDesignerUserData:{profiles:[]},tubeDesignerSelectedProfileId:'system:rect'};
  const mount=document.createElement('main');document.body.append(mount);
  const profile=catalogue.find(item=>item.id==='rect');
  mount.innerHTML=`<div class="cam-workbench"><aside class="cam-context-pane"></aside><div class="cam-viewport">${library.renderProfileLibraryDiagramDock(view,profile)}</div><aside class="cam-info-pane">${library.renderProfileLibraryRightPane({},view)}</aside></div>`;
  const context={mount};const ops={renderProject(){}};
  mount.addEventListener('click',event=>{const target=event.target.closest('[data-cam-action]');if(target)void library.handleProfileLibraryAction(context,view,target.dataset.camAction,target,ops);});
  bindProfileParameterDiagrams(mount);bindDiagramDragging(mount,view);
  window.fixture={mount,view};
 },catalogue);
 const dock=page.locator('[data-tube-profile-diagram-dock]');
 assert.equal(await dock.isVisible(),true);
 await dock.locator('[data-library-diagram-close]').click();
 assert.equal(await dock.isVisible(),false);
 await page.locator('[data-profile-diagram-toggle]').click();
 assert.equal(await dock.isVisible(),true);
 assert.ok(await dock.locator('svg').count());
 await dock.locator('[data-profile-annotation-key="width"] text').first().click();
 assert.equal(await page.evaluate(()=>document.activeElement.dataset.profileParameterKey),'width');
 const header=dock.locator('[data-floating-diagram-drag]');
 const before=await dock.boundingBox(),grip=await header.boundingBox();
 await page.mouse.move(grip.x+40,grip.y+10);await page.mouse.down();
 await page.mouse.move(grip.x-100,grip.y+50,{steps:6});await page.mouse.up();
 const after=await dock.boundingBox();assert.ok(Math.abs(after.x-before.x)>40);
 await dock.locator('[data-library-diagram-close]').click();assert.equal(await dock.isVisible(),false);
 await page.locator('[data-profile-diagram-toggle]').click();assert.equal(await dock.isVisible(),true);
 assert.deepEqual(errors,[]);
 const report={status:'passed',nativeProfile:'system:rect',libraryDiagramRetained:true,annotationFocus:true,dragging:true,closeAndReopen:true};
 writeFileSync(resolve(output,'report.json'),JSON.stringify(report,null,2));
 console.log('PASS library profile diagram opening, annotation focus, dragging, closing and reopening');
}finally{await browser.close();}
