import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { ribbonDefinition } from "../../apps/tube-designer/webpage/ribbonDefinition.mjs";
import { analyzeMachiningJobs, attachTubeMachining, handleTubeMachiningAction, handleTubeMachiningRibbonCommand, handleTubeMachiningViewportPick, machiningJobs, renderTubeMachiningDialogs, renderTubeMachiningRightPane, renderTubeMachiningViewportOverlay, selectedMachiningJob } from "../../apps/tube-designer/webpage/machiningArea.mjs";
import { editAtPoint, hasUnsavedMachiningPaths, pathEditor, sideLayout } from "../../apps/tube-designer/webpage/machiningEditor.mjs";
import { copyPaths, createPath, distance3, editPathPoint, mergePaths, pathLength, projectSidePoint, splitPath, transformPaths, unprojectSidePoint } from "../../apps/tube-designer/webpage/machiningPathGeometry.mjs";
import { machiningPathOverlay } from "../../apps/tube-designer/webpage/machiningViewport.mjs";
import { parseRenderGeometryResource } from "../../iCAX-UI/SDK/Viewport/renderResource.mjs";

const original = { ...createPath([[1, 3, 2], [11, 3, 2], [11, 3, 12]], false, "原刀路"), directions: [[0, 1, 0], [0, 1, 0], [0, 1, 0]] };
const frozen = structuredClone(original);
const copied = copyPaths([original], [original.id]);
assert.equal(copied.paths.length, 2);
assert.notEqual(copied.selectedIds[0], original.id);
assert.deepEqual(copied.paths[1].points, original.points);
assert.notEqual(copied.paths[1].points[0], original.points[0]);
const moved = transformPaths(copied.paths, copied.selectedIds, { translation: [7, 8, 9], axis: [0, 1, 0], angle: 90, pivot: [1, 3, 2] });
assert.deepEqual(moved[0], frozen);
assert.ok(distance3(moved[1].points[0], [8, 11, 11]) < 1e-8);
assert.ok(distance3(moved[1].points[1], [8, 11, 1]) < 1e-8);
assert.ok(Math.abs(pathLength(moved[1]) - pathLength(original)) < 1e-8);
assert.throws(() => transformPaths([original], [original.id], { translation: [NaN, 0, 0] }));
const split = splitPath(original, 0, .25);
assert.equal(split.length, 2);
assert.deepEqual(split[0].points.at(-1), [3.5, 3, 2]);
const joined = mergePaths(split, split.map(p => p.id));
assert.equal(joined.paths.length, 1);
assert.ok(Math.abs(pathLength(joined.paths[0]) - pathLength(original)) < 1e-8);
assert.throws(() => mergePaths([original, moved[1]], [original.id, moved[1].id]), /超过/);
const closed = createPath([[0, 0, 0], [10, 0, 0], [10, 0, 10], [0, 0, 0]], true);
assert.equal(closed.points.length, 3);
assert.equal(splitPath(closed, 0).length, 1);
assert.equal(splitPath(closed, 0)[0].closed, false);
assert.ok(Math.abs(pathLength(splitPath(closed, 0)[0]) - pathLength(closed)) < 1e-8);
assert.throws(() => createPath([[0, 0, 0], [0, 0, 0]]));
assert.deepEqual(editPathPoint(original, 1, [22, 3, 2]).points[1], [22, 3, 2]);
assert.deepEqual(original, frozen);
assert.deepEqual(unprojectSidePoint(projectSidePoint([11, 3, 12]), "XZ", 3), [11, 3, 12]);

const job = { id: "job-1", sourceKind: "cad", resourceId: "brep-1", resourceVersion: 1, name: "<test>", solidCount: 1, sourceFileName: "排样.step", analysis: { paths: [original], revision: "a1", independent: true } };
const linked = { id: "job-2", sourceKind: "nesting", planId: "plan-1", sourceRevision: "n1", analysis: { paths: [structuredClone(original)], revision: "a2" } };
const view = { activeAreaId: "machining", scene: { tubeDesigner: { machiningTask: { revision: "m1", jobs: [job, linked] }, nestingGroups: [], nestingTask: { revision: "n1", result: { plans: [{ id: "plan-1", stockLength: 1000, placements: [] }] } } } } };
const calls = [], ops = { renderProject() {}, showNotice() {} };
const context = { sceneProxy: { async invoke(method, payload) {
  calls.push({ method, payload: structuredClone(payload) });
  const source = view.scene.tubeDesigner;
  if (method === "TubeDesigner.List") return { tubeDesigner: source };
  const task = structuredClone(source.machiningTask);
  if (payload.action === "analyze") for (const j of task.jobs) if (payload.jobIds.includes(j.id)) j.analysis = { paths: [createPath([[0, 2, 0], [30, 2, 0]])], revision: `analyzed-${calls.length}` };
  if (payload.action === "save-paths") for (const j of task.jobs) if (payload.jobIds.includes(j.id)) j.analysis = { paths: payload.paths, revision: `saved-${calls.length}` };
  if (payload.action === "preview") return { geometryResourceId: "mesh", geometryResourceVersion: 1 };
  task.revision = `m${calls.length + 1}`;
  return { machiningTask: task, nestingTask: source.nestingTask, jobId: payload.jobIds?.[0] ?? "job-1" };
} }, actions: { async selectRibbonTab() {} } };
const editor = pathEditor(view, job);
assert.notEqual(editor.paths[0], original);
await handleTubeMachiningAction(context, view, "tube-path-select", { dataset: { pathId: original.id } }, ops);
assert.deepEqual(editor.selectedIds, [original.id]);
await handleTubeMachiningAction(context, view, "tube-path-copy", {}, ops);
assert.equal(editor.paths.length, 2);
assert.ok(hasUnsavedMachiningPaths(view));
await handleTubeMachiningAction(context, view, "tube-path-undo", {}, ops);
assert.equal(editor.paths.length, 1);
await handleTubeMachiningAction(context, view, "tube-path-redo", {}, ops);
assert.equal(editor.paths.length, 2);
await handleTubeMachiningAction(context, view, "tube-path-save", {}, ops);
assert.equal(view.scene.tubeDesigner.machiningTask.jobs[0].analysis.paths.length, 2);
assert.equal(pathEditor(view, selectedMachiningJob(view)).dirty, false);
const before = calls.length;
let confirms = 0;
assert.equal(await analyzeMachiningJobs(context, view, [selectedMachiningJob(view)], ops, async message => { confirms++; assert.match(message, /丢弃/); return false; }), false);
assert.equal(calls.length, before);
const untouched = structuredClone(view.scene.tubeDesigner.machiningTask.jobs[1].analysis);
await analyzeMachiningJobs(context, view, [selectedMachiningJob(view)], ops, async () => { confirms++; return true; });
assert.equal(confirms, 2);
assert.deepEqual(view.scene.tubeDesigner.machiningTask.jobs[1].analysis, untouched);
assert.equal(view.scene.tubeDesigner.machiningTask.jobs[0].analysis.paths.length, 1);
await analyzeMachiningJobs(context, view, machiningJobs(view), ops, async () => true);
assert.deepEqual(calls.at(-1).payload.jobIds, ["job-1", "job-2"]);

view.scene.tubeDesigner.nestingTask = { revision: "new-source", result: {} };
const stale = machiningJobs(view).find(j => j.id === "job-2");
assert.equal(stale.stale, true);
assert.ok(stale.analysis.paths.length);
const staleEditor = pathEditor(view, stale);
const staleSaved = structuredClone(staleEditor.paths);
staleEditor.mode = "draw";
editAtPoint(staleEditor, [10, 6, 0]); editAtPoint(staleEditor, [20, 6, 0]);
assert.deepEqual(staleEditor.paths, staleSaved);

view.tubeDesignerMachining.selectedId = "job-1";
const currentJob = selectedMachiningJob(view), e = pathEditor(view, currentJob), p = e.paths[0];
const hit = { object: { userData: { objectId: `machining-path:${p.id}` } }, point: { x: 0, y: 2, z: 0 } };
assert.equal(handleTubeMachiningViewportPick(context, view, null, hit, {}, [hit], ops), true);
assert.deepEqual(e.selectedIds, [p.id]);
assert.match(renderTubeMachiningRightPane(context, view), /刀路列表[\s\S]*刀路属性/);
assert.match(renderTubeMachiningRightPane(context, view), /&lt;test&gt;/);
const overlay = machiningPathOverlay(view, currentJob);
assert.ok(overlay.rows.some(r => r.entityId === `machining-path:${p.id}`));
for (const row of overlay.rows) assert.equal(parseRenderGeometryResource(overlay.resources.get(row.data.geometry.url)).kind, "polyline");
e.space = "2d";
assert.match(renderTubeMachiningViewportOverlay(context, view), /data-machining-side-canvas/);
const layout = sideLayout(e), [x, y] = layout.project(p.points[0]);
assert.ok(distance3(layout.unproject(x, y, p.points[0][1]), p.points[0]) < 1e-8);
e.space = "3d"; e.mode = "draw";
view.viewport = { pointOnWorkPlane() { return [14, 7, 22]; } };
handleTubeMachiningViewportPick(context, view, null, null, { clientX: 100, clientY: 100 }, [], ops);
assert.deepEqual(e.drawing.at(-1), [14, 7, 22]);
assert.deepEqual(original, frozen);

const tab = ribbonDefinition.tabs.find(t => t.id === "machining");
assert.equal(ribbonDefinition.tabs[ribbonDefinition.tabs.findIndex(t => t.id === "nesting") + 1], tab);
assert.ok(tab.groups.flatMap(g => g.commands).every(c => !c.menuItems?.length));
assert.ok(tab.groups.flatMap(g => g.commands).some(c => c.id === "machining.analyze-all"));
const service = await readFile(new URL("../../iCAX-Plugins/cam/BRepToCamPath/BRepToCamPathService.h", import.meta.url), "utf8");
assert.match(service, /CamPathAnalysis Analyze\(const iCAX::GeometryData::BRepModel&/);
assert.doesNotMatch(service, /ISceneContext|ObjectMap/);
const snapshots = [];
const missingCadView = { activeAreaId: "machining", scene: { tubeDesigner: { machiningTask: { jobs: [job] } } },
  viewport: { setVisibleEntityIds() {}, async applyViewSnapshot(snapshot) { snapshots.push(snapshot); return { applied: true }; } } };
attachTubeMachining({ sceneProxy: { async invoke() { throw new Error("CAD missing"); } } }, missingCadView, null, ops);
await missingCadView.tubeDesignerMachining.preview.promise;
assert.ok(snapshots.at(-1).rows.some(row => row.entityId === `machining-path:${original.id}`));
assert.equal(missingCadView.tubeDesignerMachining.preview.ready, true);
assert.match(missingCadView.tubeDesignerMachining.preview.error, /CAD 背景不可用/);
console.log("TubeDesigner machining tests passed: sources, independent paths, replacement confirmation, copy/transform/split/merge, 2D/3D selection and persistence.");
