import assert from "node:assert/strict";
import {handleLicenseCommand, renderLicenseStatus} from "../../apps/tube-designer/webpage/licensing.mjs";
import {renderAboutRightPane} from "../../apps/tube-designer/webpage/aboutArea.mjs";
import {ribbonDefinition} from "../../apps/tube-designer/webpage/ribbonDefinition.mjs";
const calls = [];
assert.match(renderLicenseStatus({tubeDesignerLicense: {developmentBypass: true, activated: false, message: "Debug"}}), /开发免授权/);
const context = {productProxy: {invoke: async (name, payload) => {
  calls.push([name,payload]); return {activated:true,kind:"永久授权",licenseId:"example",features:15};
}, bridge: {openDirectoryDialog: async () => "D:\\授权", openFileDialog: async () => "D:\\激活.tdact"}}};
const view = {};
const ops = {renderProject: () => {}};
assert.equal(await handleLicenseCommand(context, view, "other", ops), false);
await handleLicenseCommand(context, view, "licensing.request", ops);
assert.equal(calls.at(-1)[0], "TubeDesignerLicensing.Request");
assert.match(calls.at(-1)[1].path, /^D:\\授权\\TubeDesigner-.*\.tdreq$/);
await handleLicenseCommand(context, view, "licensing.request-trial", ops);
assert.equal(calls.at(-1)[0], "TubeDesignerLicensing.RequestTrial");
await handleLicenseCommand(context, view, "licensing.activate", ops);
assert.equal(calls.at(-1)[0], "TubeDesignerLicensing.Activate");
assert.equal(view.pending, false);
assert.equal(view.tubeDesignerLicense.activated, true);
await handleLicenseCommand(context, view, "licensing.status", ops);
assert.equal(calls.at(-1)[0], "TubeDesignerLicensing.Status");
assert.match(renderAboutRightPane(context, view), /软件授权/);
assert.ok(!renderLicenseStatus({tubeDesignerLicense:{message:'<script>alert(1)</script>'}}).includes("<script>"));
context.productProxy.invoke = async () => { throw new Error("TPM error"); };
await handleLicenseCommand(context, view, "licensing.status", ops);
assert.equal(view.pending, false);
assert.equal(view.error, "TPM error");
assert.equal(ribbonDefinition.tabs.find(t => t.id === "about").groups[0].commands.length, 4);
console.log("TubeDesigner licensing UI tests passed");
