"""Generate the compiled license capability catalog from the shared descriptor."""
import argparse
import json
from pathlib import Path


def generate(root: Path) -> str:
    catalog = json.loads((root / "features.json").read_text(encoding="utf-8"))
    if catalog["schemaVersion"] != 1 or catalog["certificateFormat"] != "TDLIC003":
        raise ValueError("Unknown capability schema")
    features = catalog["features"]
    ids, bits = set(), set()
    names = {}
    for feature in features:
        identifier, bit = feature["id"], feature["bit"]
        if identifier in ids or isinstance(bit, bool) or not isinstance(bit, int) or bit <= 0 or bit > 0x80000000 or bit & (bit - 1) or bit in bits:
            raise ValueError("Invalid or duplicate feature")
        ids.add(identifier)
        bits.add(bit)
        names[identifier] = "".join(part[0].upper() + part[1:] for part in identifier.split("."))
    for feature in features:
        parent = feature["parent"]
        if parent is not None and (parent not in ids or not parent.startswith("page.") or parent == feature["id"]):
            raise ValueError("Invalid feature parent")
    enum = "\n".join(f'    {names[f["id"]]} = {f["bit"]},' for f in features)
    rows = "\n".join(
        f'    {{Feature::{names[f["id"]]}, "{f["id"]}", "{f["label"]}", {0 if f["parent"] is None else next(p["bit"] for p in features if p["id"] == f["parent"])}}},'
        for f in features
    )
    return f'''#pragma once
// Generated by src/licensing/generate_feature_catalog.py from features.json.
// Do not maintain separate authorization bits in native clients or issuer UI.
#include <array>
#include <cstdint>
#include <string_view>

namespace tube::license {{
enum class Feature : std::uint32_t {{
{enum}
}};
inline constexpr std::uint32_t FeatureSchemaVersion = {catalog["schemaVersion"]};
inline constexpr std::uint32_t KnownFeatures = {sum(bits)};
inline constexpr std::string_view CertificateFormat = "{catalog["certificateFormat"]}";
struct FeatureDescriptor final {{
    Feature feature;
    std::string_view id, label;
    std::uint32_t parent;
}};
inline constexpr std::array<FeatureDescriptor, {len(features)}> FeatureCatalog{{{{
{rows}
}}}};
inline constexpr std::uint32_t RequiredFeatures(Feature feature) {{
    for (const auto& descriptor : FeatureCatalog)
        if (descriptor.feature == feature) return static_cast<std::uint32_t>(feature) | descriptor.parent;
    return 0;
}}
inline constexpr bool HasFeature(std::uint32_t granted, Feature feature) {{
    const auto required = RequiredFeatures(feature);
    return required != 0 && (granted & required) == required;
}}
inline constexpr bool IsValidFeatureSet(std::uint32_t granted) {{
    if (granted == 0 || (granted & ~KnownFeatures) != 0) return false;
    for (const auto& descriptor : FeatureCatalog)
        if ((granted & static_cast<std::uint32_t>(descriptor.feature)) != 0 &&
            (granted & descriptor.parent) != descriptor.parent) return false;
    return true;
}}
}}
'''


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    path = root / "include" / "FeatureCatalog.generated.h"
    contents = generate(root)
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != contents:
            raise SystemExit("Native feature catalog differs from features.json; regenerate it")
    else:
        path.write_text(contents, encoding="utf-8", newline="\n")
