// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace iCAX.Sample
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MyStruct2 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static MyStruct2 GetRootAsMyStruct2(ByteBuffer _bb) { return GetRootAsMyStruct2(_bb, new MyStruct2()); }
  public static MyStruct2 GetRootAsMyStruct2(ByteBuffer _bb, MyStruct2 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool MyStruct2BufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "SMPL"); }
  public static bool VerifyMyStruct2(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("SMPL", false, MyStruct2Verify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MyStruct2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int R { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<iCAX.Sample.MyStruct2> CreateMyStruct2(FlatBufferBuilder builder,
      int R = 0) {
    builder.StartTable(1);
    MyStruct2.AddR(builder, R);
    return MyStruct2.EndMyStruct2(builder);
  }

  public static void StartMyStruct2(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddR(FlatBufferBuilder builder, int r) { builder.AddInt(0, r, 0); }
  public static Offset<iCAX.Sample.MyStruct2> EndMyStruct2(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<iCAX.Sample.MyStruct2>(o);
  }
  public static void FinishMyStruct2Buffer(FlatBufferBuilder builder, Offset<iCAX.Sample.MyStruct2> offset) { builder.Finish(offset.Value, "SMPL"); }
  public static void FinishSizePrefixedMyStruct2Buffer(FlatBufferBuilder builder, Offset<iCAX.Sample.MyStruct2> offset) { builder.FinishSizePrefixed(offset.Value, "SMPL"); }
}


static public class MyStruct2Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*R*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
