// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace iCAX.Sample
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MyStruct1 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static MyStruct1 GetRootAsMyStruct1(ByteBuffer _bb) { return GetRootAsMyStruct1(_bb, new MyStruct1()); }
  public static MyStruct1 GetRootAsMyStruct1(ByteBuffer _bb, MyStruct1 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool MyStruct1BufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "SMPL"); }
  public static bool VerifyMyStruct1(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("SMPL", false, MyStruct1Verify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MyStruct1 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int A { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int B { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<iCAX.Sample.MyStruct1> CreateMyStruct1(FlatBufferBuilder builder,
      int A = 0,
      int B = 0) {
    builder.StartTable(2);
    MyStruct1.AddB(builder, B);
    MyStruct1.AddA(builder, A);
    return MyStruct1.EndMyStruct1(builder);
  }

  public static void StartMyStruct1(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddA(FlatBufferBuilder builder, int a) { builder.AddInt(0, a, 0); }
  public static void AddB(FlatBufferBuilder builder, int b) { builder.AddInt(1, b, 0); }
  public static Offset<iCAX.Sample.MyStruct1> EndMyStruct1(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<iCAX.Sample.MyStruct1>(o);
  }
  public static void FinishMyStruct1Buffer(FlatBufferBuilder builder, Offset<iCAX.Sample.MyStruct1> offset) { builder.Finish(offset.Value, "SMPL"); }
  public static void FinishSizePrefixedMyStruct1Buffer(FlatBufferBuilder builder, Offset<iCAX.Sample.MyStruct1> offset) { builder.FinishSizePrefixed(offset.Value, "SMPL"); }
}


static public class MyStruct1Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*A*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*B*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
