// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAMPLESTRUCT2_ICAX_SAMPLE_H_
#define FLATBUFFERS_GENERATED_SAMPLESTRUCT2_ICAX_SAMPLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace iCAX {
namespace Sample {

struct MyStruct2;
struct MyStruct2Builder;
struct MyStruct2T;

struct MyStruct2T : public ::flatbuffers::NativeTable {
  typedef MyStruct2 TableType;
  int32_t R = 0;
};

struct MyStruct2 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MyStruct2T NativeTableType;
  typedef MyStruct2Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_R = 4
  };
  int32_t R() const {
    return GetField<int32_t>(VT_R, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_R, 4) &&
           verifier.EndTable();
  }
  MyStruct2T *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MyStruct2T *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MyStruct2> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct2T* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MyStruct2Builder {
  typedef MyStruct2 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_R(int32_t R) {
    fbb_.AddElement<int32_t>(MyStruct2::VT_R, R, 0);
  }
  explicit MyStruct2Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MyStruct2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MyStruct2>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MyStruct2> CreateMyStruct2(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t R = 0) {
  MyStruct2Builder builder_(_fbb);
  builder_.add_R(R);
  return builder_.Finish();
}

::flatbuffers::Offset<MyStruct2> CreateMyStruct2(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct2T *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline MyStruct2T *MyStruct2::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MyStruct2T>(new MyStruct2T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MyStruct2::UnPackTo(MyStruct2T *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = R(); _o->R = _e; }
}

inline ::flatbuffers::Offset<MyStruct2> MyStruct2::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct2T* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMyStruct2(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MyStruct2> CreateMyStruct2(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct2T *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MyStruct2T* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _R = _o->R;
  return iCAX::Sample::CreateMyStruct2(
      _fbb,
      _R);
}

inline const iCAX::Sample::MyStruct2 *GetMyStruct2(const void *buf) {
  return ::flatbuffers::GetRoot<iCAX::Sample::MyStruct2>(buf);
}

inline const iCAX::Sample::MyStruct2 *GetSizePrefixedMyStruct2(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<iCAX::Sample::MyStruct2>(buf);
}

inline const char *MyStruct2Identifier() {
  return "SMPL";
}

inline bool MyStruct2BufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MyStruct2Identifier());
}

inline bool SizePrefixedMyStruct2BufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MyStruct2Identifier(), true);
}

inline bool VerifyMyStruct2Buffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<iCAX::Sample::MyStruct2>(MyStruct2Identifier());
}

inline bool VerifySizePrefixedMyStruct2Buffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<iCAX::Sample::MyStruct2>(MyStruct2Identifier());
}

inline void FinishMyStruct2Buffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<iCAX::Sample::MyStruct2> root) {
  fbb.Finish(root, MyStruct2Identifier());
}

inline void FinishSizePrefixedMyStruct2Buffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<iCAX::Sample::MyStruct2> root) {
  fbb.FinishSizePrefixed(root, MyStruct2Identifier());
}

inline std::unique_ptr<iCAX::Sample::MyStruct2T> UnPackMyStruct2(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<iCAX::Sample::MyStruct2T>(GetMyStruct2(buf)->UnPack(res));
}

inline std::unique_ptr<iCAX::Sample::MyStruct2T> UnPackSizePrefixedMyStruct2(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<iCAX::Sample::MyStruct2T>(GetSizePrefixedMyStruct2(buf)->UnPack(res));
}

}  // namespace Sample
}  // namespace iCAX

#endif  // FLATBUFFERS_GENERATED_SAMPLESTRUCT2_ICAX_SAMPLE_H_
