// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAMPLESTRUCT1_ICAX_SAMPLE_H_
#define FLATBUFFERS_GENERATED_SAMPLESTRUCT1_ICAX_SAMPLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace iCAX {
namespace Sample {

struct MyStruct1;
struct MyStruct1Builder;
struct MyStruct1T;

struct MyStruct1T : public ::flatbuffers::NativeTable {
  typedef MyStruct1 TableType;
  int32_t A = 0;
  int32_t B = 0;
};

struct MyStruct1 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MyStruct1T NativeTableType;
  typedef MyStruct1Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_A = 4,
    VT_B = 6
  };
  int32_t A() const {
    return GetField<int32_t>(VT_A, 0);
  }
  int32_t B() const {
    return GetField<int32_t>(VT_B, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_A, 4) &&
           VerifyField<int32_t>(verifier, VT_B, 4) &&
           verifier.EndTable();
  }
  MyStruct1T *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MyStruct1T *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MyStruct1> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct1T* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MyStruct1Builder {
  typedef MyStruct1 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_A(int32_t A) {
    fbb_.AddElement<int32_t>(MyStruct1::VT_A, A, 0);
  }
  void add_B(int32_t B) {
    fbb_.AddElement<int32_t>(MyStruct1::VT_B, B, 0);
  }
  explicit MyStruct1Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MyStruct1> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MyStruct1>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MyStruct1> CreateMyStruct1(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t A = 0,
    int32_t B = 0) {
  MyStruct1Builder builder_(_fbb);
  builder_.add_B(B);
  builder_.add_A(A);
  return builder_.Finish();
}

::flatbuffers::Offset<MyStruct1> CreateMyStruct1(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct1T *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline MyStruct1T *MyStruct1::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MyStruct1T>(new MyStruct1T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MyStruct1::UnPackTo(MyStruct1T *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = A(); _o->A = _e; }
  { auto _e = B(); _o->B = _e; }
}

inline ::flatbuffers::Offset<MyStruct1> MyStruct1::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct1T* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMyStruct1(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MyStruct1> CreateMyStruct1(::flatbuffers::FlatBufferBuilder &_fbb, const MyStruct1T *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MyStruct1T* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _A = _o->A;
  auto _B = _o->B;
  return iCAX::Sample::CreateMyStruct1(
      _fbb,
      _A,
      _B);
}

inline const iCAX::Sample::MyStruct1 *GetMyStruct1(const void *buf) {
  return ::flatbuffers::GetRoot<iCAX::Sample::MyStruct1>(buf);
}

inline const iCAX::Sample::MyStruct1 *GetSizePrefixedMyStruct1(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<iCAX::Sample::MyStruct1>(buf);
}

inline const char *MyStruct1Identifier() {
  return "SMPL";
}

inline bool MyStruct1BufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MyStruct1Identifier());
}

inline bool SizePrefixedMyStruct1BufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MyStruct1Identifier(), true);
}

inline bool VerifyMyStruct1Buffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<iCAX::Sample::MyStruct1>(MyStruct1Identifier());
}

inline bool VerifySizePrefixedMyStruct1Buffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<iCAX::Sample::MyStruct1>(MyStruct1Identifier());
}

inline void FinishMyStruct1Buffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<iCAX::Sample::MyStruct1> root) {
  fbb.Finish(root, MyStruct1Identifier());
}

inline void FinishSizePrefixedMyStruct1Buffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<iCAX::Sample::MyStruct1> root) {
  fbb.FinishSizePrefixed(root, MyStruct1Identifier());
}

inline std::unique_ptr<iCAX::Sample::MyStruct1T> UnPackMyStruct1(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<iCAX::Sample::MyStruct1T>(GetMyStruct1(buf)->UnPack(res));
}

inline std::unique_ptr<iCAX::Sample::MyStruct1T> UnPackSizePrefixedMyStruct1(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<iCAX::Sample::MyStruct1T>(GetSizePrefixedMyStruct1(buf)->UnPack(res));
}

}  // namespace Sample
}  // namespace iCAX

#endif  // FLATBUFFERS_GENERATED_SAMPLESTRUCT1_ICAX_SAMPLE_H_
