#pragma once
// Generated by src/licensing/generate_feature_catalog.py from features.json.
// Do not maintain separate authorization bits in native clients or issuer UI.
#include <array>
#include <cstdint>
#include <string_view>

namespace tube::license {
enum class Feature : std::uint32_t {
    PageProduct = 1,
    PageNesting = 2,
    PageMachining = 4,
    PageSimulation = 8,
    ProductDesign = 16,
    ProductBreakdown = 32,
    ProductExport = 64,
    NestingEdit = 128,
    NestingCalculate = 256,
    NestingExport = 512,
    MachiningToolpath = 1024,
    MachiningExport = 2048,
    SimulationRun = 4096,
};
inline constexpr std::uint32_t FeatureSchemaVersion = 1;
inline constexpr std::uint32_t KnownFeatures = 8191;
inline constexpr std::string_view CertificateFormat = "TDLIC003";
struct FeatureDescriptor final {
    Feature feature;
    std::string_view id, label;
    std::uint32_t parent;
};
inline constexpr std::array<FeatureDescriptor, 13> FeatureCatalog{{
    {Feature::PageProduct, "page.product", "产品页", 0},
    {Feature::PageNesting, "page.nesting", "下料页", 0},
    {Feature::PageMachining, "page.machining", "加工页", 0},
    {Feature::PageSimulation, "page.simulation", "仿真页", 0},
    {Feature::ProductDesign, "product.design", "产品设计", 1},
    {Feature::ProductBreakdown, "product.breakdown", "产品拆单", 1},
    {Feature::ProductExport, "product.export", "产品导出", 1},
    {Feature::NestingEdit, "nesting.edit", "下料零件编辑", 2},
    {Feature::NestingCalculate, "nesting.calculate", "排样计算", 2},
    {Feature::NestingExport, "nesting.export", "下料导出", 2},
    {Feature::MachiningToolpath, "machining.toolpath", "加工刀路", 4},
    {Feature::MachiningExport, "machining.export", "加工导出", 4},
    {Feature::SimulationRun, "simulation.run", "运行仿真", 8},
}};
inline constexpr std::uint32_t RequiredFeatures(Feature feature) {
    for (const auto& descriptor : FeatureCatalog)
        if (descriptor.feature == feature) return static_cast<std::uint32_t>(feature) | descriptor.parent;
    return 0;
}
inline constexpr bool HasFeature(std::uint32_t granted, Feature feature) {
    const auto required = RequiredFeatures(feature);
    return required != 0 && (granted & required) == required;
}
inline constexpr bool IsValidFeatureSet(std::uint32_t granted) {
    if (granted == 0 || (granted & ~KnownFeatures) != 0) return false;
    for (const auto& descriptor : FeatureCatalog)
        if ((granted & static_cast<std::uint32_t>(descriptor.feature)) != 0 &&
            (granted & descriptor.parent) != descriptor.parent) return false;
    return true;
}
}
